/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sunset */

#ifndef _Included_Sunset
#define _Included_Sunset
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sunset
 * Method:    sumar
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Sunset_sumar
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     Sunset
 * Method:    restar
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Sunset_restar
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     Sunset
 * Method:    multiplicar
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Sunset_multiplicar
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     Sunset
 * Method:    dividir
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Sunset_dividir
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     Sunset
 * Method:    comparar
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_Sunset_comparar
  (JNIEnv *, jobject, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
